# Uvod u NumPy

[NumPy](https://numpy.org/doc/stable/index.html) je Python biblioteka otvorenog koda koja se koristi za obradu numeričkih podatka u Pythonu. To je najveća, najpopularnija i najpodržanija biblioteka takvog tipa. Mnoge druge biblioteke nastale su kao nadogradnja NumPya ili ga koriste kao polazišnu točku. Primjeri takvih bibilioteka su [Pandas](https://pandas.pydata.org/), [scikit-learn](https://scikit-learn.org/stable/), [SciPy](https://scipy.org/) i mnoge druge. U ovoj Jupyter bilježnice upoznati ćemo se s osnovama NumPya. 

Strojno učenje radi s podatcima, koji mogu biti numerički i/ili kategorički, te je upravo NumPy okosnica mnogih biblioteka strojnog učenja koje rade s numeričkim podatcima.

Poput bilo koje druge Python biblioteke NumPy je potrebno *importati* to jest povezati s ostatkom našeg programa. U pravilu se *importa* cijeli modul i to kao skraćenicu `np` 

In [1]:
import numpy as np

## Stvaranje ndarrayeva

Osnovni element NumPya je `np.ndarray`, to jest n-dimenzionalna lista. To je nadogradnja osnovne Python liste, optimizirana za razne oblike pristupa, transformacija i numeričkih operacija. `np.ndarray` za razliku od obične liste mora biti homogen, to jest svi elemnti moraju biti istog tipa. Pošto NumPy interno poziva efikasne funkcije pisane u jeziku c, podatci moraju biti kompatiblini. U pravilu `np.ndarray` iz već postojećih podataka stvaramo pomoću funkcije `np.array`, koja prime *array-like* objekt i stvara `np.ndarray`.

In [2]:
# basic array creation from list
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [3]:
# 2d array from list of lists
a = np.array([
  [1,2,3],
  [4,5,6],
  [7,8,9]
])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Često moramo stvariti matematičke objekte koji su unaprijed definirani, poput nul-vektora, jedinične matrice, dijagonalne matrice iz vektora i slično. NumPy ima brojne funkcije kojima se možemo poslužiti. No prije njih, moramo objasniti `shape` atribut. Svaki `np.ndarray` ima svoj `shape` atribut koji opisuje dimenzije objekta. 

In [4]:
a.shape

(3, 3)

`shape` je tuple, u kojem se nalaze dimenzije. U terminima matrica, prvi broj predstavlja broj redaka, a drugi broj stupaca. Prethodno definirana matrica `a` ima 3 redka i 3 stupca.

In [5]:
np.zeros((2,3))  # create array of specified shape filled with zeros.


array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.eye(3)  # I matrix of dimensions 3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
np.diag([1,2,3])  # Create diagaonal matrix from an 1-d array like object

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [8]:
np.full_like(a, 1)  # Create an array with shape of a filled with ones, same as np.full(a.shape, 1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

Pošto `ndarray` može imati proizvoljno mnogo dimenzija, NumPy koristi koncept osi (`axis`) kako bi se po njima kretali. Osi se indeksiraju od 0. "Redci" matrice su os 0, a "stupci" 1. Primjerice kada ćemo raditi agregacije nad `ndarrayevima`, moći ćemo specificirati po kojim ćemo ih osima raditi ili pak želimo li ih raditi nad svim elementima.

## Pristup, transformacije i kombiniranje

Nakon upoznavanja s nekim od osnovnih načina stvarnja arrayeva, upoznat ćemo se s načinima pristupa, *slicinga* i kombiniranja arrayeva. Najosnovnija vrsta pristupa identična je pristupu običnoj Python listi. N dimenzionalan array se ustvari sastoji od *k* N-1 dimenzionalnih arrayeva. Klasičnim pristupom pomoću uglatih zagrada mi ćemo dohvatiti jedan od N-1 dimenzionalnih *subarrayeva*, a ne konkretan broj. U jednodimenzionalnom slučaju pristupit ćemo skalaru, to jest broju.

In [9]:
#  1d element access
a[0]

array([1, 2, 3])

No kako da pristupimo konkretnom broju naše matrice `a`? Pa sjetimo se rekurzivne naravi `np.ndarray`-a, ako je `a` dvodimenzionalan array, onda je `a[0]` jednodimenzionalan array, to jest `a[0][0]` je upravo "prvi" element matrice. Pošto možemo imati proizvoljno mnogo dimenzija, ne želimo da nam kod ovisi o sintaksi. Primjerice ako napišemo funkciju:
```py
def add_one_to_elem(matrix, row, col):
    matrix[row][column] += 1
```

Ova funkcija može raditi samo sa dvodminezionalnim objektima. NumPy to rješava na zanimljiv način, umjesto da indeks može biti samo broj indeks može biti i tuple, to jest uređena n-torka elemenata. Primjerice prvom elementu naše matrice `a` možemo pristupiti izrazom `a[0,0]`. Primjetite da je u Pythonu `0,0` ista stvar što i `(0,0)`.

In [10]:
# 2d element access
a[0,2]


3

Sada našu ograničenu funkciju možemo napisati kao 
```py
def add_one_to_elem(matrix, position):
    matrix[position] += 1
```
Ova funkcija sada može raditi s ndarrayem bilo koje dimenzije, jedino treba paziti da je `position` validan indeks predane matrice. 

Možemo dohvatiti i više elemenata istodobno, tada umjesto tuplea indeksa, predajemo tuple *array-like* objekata. Bitno je da su ti objekti jednake duljine. NumPy tada sparuje odgovarajuće pozicije i po njima indeksira. 

In [11]:
# multiple element access
a[[0,1,2],[0,1,2]]

array([1, 5, 9])

Često želimo pristupiti samo onim elementima koji zadovoljavaju neki logički uvjet, to jest elemente želimo *filtrirati*. NumPy to elegantno omogućuje. Pogledajmo primjere:

In [12]:
# get all elements larger than 5
a[a > 5]


array([6, 7, 8, 9])

In [13]:
a[a % 2 == 0]

array([2, 4, 6, 8])

Ovo je pomalo neočekivano. Od pametnog, ali svakodnevnog, pristupa pomoću indeksa, došli smo do toga da odjednom možemo pristupati po logičkim predikatima. NumPy *overloada* operatore, što to konkretno znači? To znači da primjerice dobro nam znam operator `+` za različite *tipove* obavlja različite funkcije. Logički su operatori primjerice *overloadani* na način da nad svakim elementom matrice izvrše logičku operaciju. Pogledajmo primjer:

In [14]:
a > 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

Vidimo da NumPy vraća `ndarray` istih dimnezija, ali drukčijeg tipa. Konkretno tipovi su `bool`. Vidimo da također možemo indeskirati i po drugom `ndarrayu`. Jednostavno ćemo dohvatiti elemente s onih pozicija na kojima se nalazi `True`. 

Klasične python liste možemo `slice`-ati, to jest pristupati podlistama originalne liste. Ista stvar je moguća i kod `ndarrayeva`. Jednostavno specificiramo početne i završne indekse osi i dohvatimo `subarray`.

In [15]:
a[0:2,0:2]

array([[1, 2],
       [4, 5]])

Ako bi smo htjeli primjerice izvući srednji stupac, možemo specificirati da pristupamo svim redcima, a iz svakog samo srednjem elementu. U slučaju dobro nam poznate matrice `a` to je stupac s indeksom `1`.

In [16]:
#get middle column
a[:, 1]

array([2, 5, 8])

Treba pripaziti na jednu stvar, radi uštede memorije NumPy, kada može, radi plitke kopije ([shallow copy](https://stackoverflow.com/questions/184710/what-is-the-difference-between-a-deep-copy-and-a-shallow-copy)) to jest vraća reference na već postojeće elemente. to zvuči izvrsno, naime stvarno želimo umanjiti zauzeće memorije što je više moguće. Međutim treba paziti, da onda dijelimo isti podataka između dvije varijable. Ilustrirajmo sada jedan suptilan *bug*.

In [17]:
original = np.array([
  [1,2],
  [3,4]
])

first_row = original[0]

first_row[0] = 1000

original

array([[1000,    2],
       [   3,    4]])

Naime, izmjenom elementa u našem vektor-retku `first_row`, promijenili smo i vrijednost matrice `original`, na poziciji `(0,0)`. Više informacija o ovom možete pronaći na sljedećoj [poveznici](https://numpy.org/doc/stable/user/basics.copies.html). Za potrebe ovog kolegija, ako ćemo morati mutirati podmatrice, prvo ćemo *sliceati*, a potom kopirati.


Sada ćemo se upoznati sa osnovama kombiniranja postojećih `ndarraya` u nove. 


In [18]:
a_1 = np.array([
  [1,1],
  [2,2]
])

a_2 = np.array([
  [3,3],
  [4,4]
])



Napravili smo dva `ndarraya` dimenzija `2x2`. Sada ćemo ih kombinirati.

In [19]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [20]:
np.vstack((a_1, a_2))


array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

NumPy pruža dvije funkcije; `np.hstack` i `np.vstack`. Te funkcije, kao prvi argument, primaju `tuple` (n-torku) `ndarrayeva` koje zatim spajaju. `np.hstack`, spaja arrayeve horizontalno, to jest po stupcima. Primjetimo da se sada krećemo po drugoj osi (*axis*), to jest osi s indeksom 1. `np.vstack` radi identičnu stvar, samo se sada krećemo po prvoj osi, to jest vertikalno kombiniramo arrayeve. Ovu funkcionalnost možemo postići na više načina.

In [21]:
np.concatenate([a_1, a_2], axis=0)

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [22]:
np.r_[a_1, a_2]

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

Pomoću `np.concatenate` možemo pretvoriti array-like objekt dimenzije `N` u array-like objekt dimenzije `N-1` spajanjem subarrayeva po specificiranoj osi. Ovo je korisno kod višedimenzionalnih arrayeva, gdje nemamo specifične funkcije za pojedine osi. Ako bi u pozivu funkcije `axis=0` zamijenili s `axis=1`, dobili bismo funkciju ekvivalentnu funkciji `np.hstack`.

Pomoću objekta `np.r_` možemo sintaksom sličnoj indeksaciji spajati arrayeve. `np.r_` spojit će predane argumente kao retke, to jest na isti način kao i `np.vstack`. Ekivalentni objekt za spajanje po stupcima je `np.c_`. 

Preporuka je koristiti `np.hstack` i `np.vstack` metode gdje je to moguće, a `np.r_` i `np.c_` navedeni su u sluačju da se s njima susretnete u nekom drugom kodu.

Pošto ćemo često baratati matricama korisno je upoznati se i s načinima kako te iste matrice i transponirati. To je naime relativno jednostavno, postoji funkcija `np.transpose` koja jednostavno retke zapiše kao stupce. 

In [23]:
np.transpose(a)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Također, kako bi mogli emulirati matematički zapis formula, NumPy podržava i sljedeću operaciju.

In [24]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Za kraj upoznat ćemo se još s `ndarray.reshape`. To je jako korisna, i idiomatska metoda u NumPyu. Ta metoda kao argument prima shape, i vraća transformirani objekt. Transformirani objekt upravo ima predani shape. Naravno treba paziti da se početni i završni shape poklapaju.
Konkretno array s shapeom `(2,3)` možemo preoblikovati u array shapea `(3,2)` (primjetite da je to jednako transpoziciji!), dok array sa shapeom `(5,2)` ne možemo transformirati u array shapea `(4,3)`. Pogledajmo:

In [25]:
arr = np.random.randint(1,10, size=(4,6))
arr

array([[6, 3, 9, 2, 1, 7],
       [8, 9, 5, 1, 1, 2],
       [6, 6, 9, 3, 6, 4],
       [2, 3, 8, 3, 8, 5]])

In [26]:
arr.reshape((-1,8))

array([[6, 3, 9, 2, 1, 7, 8, 9],
       [5, 1, 1, 2, 6, 6, 9, 3],
       [6, 4, 2, 3, 8, 3, 8, 5]])

In [27]:
arr.reshape((3,-1))

array([[6, 3, 9, 2, 1, 7, 8, 9],
       [5, 1, 1, 2, 6, 6, 9, 3],
       [6, 4, 2, 3, 8, 3, 8, 5]])

In [28]:
arr.reshape((11,-1))

ValueError: cannot reshape array of size 24 into shape (11,newaxis)

In [ ]:
arr.reshape((2,12))

Treba obratiti pažnju da se elementi prvo uzimaju iz osi s najmanjim indeksom. Konkretno prvo ćemo uzeti sve elemente iz prvog retka, pa tek onda iz drugog.

## Agregacije

Podsjetimo se opet naše matrice `a` prije ikakvih transpozicija.

In [ ]:
a

Željeli bi smo moći raditi razne agregacije nad našim podatcima. Primjerice pronalazak maksimalnog elementa, srednje vrijednosti elemnata ili pak sume svih elemnata su često potrebne operacije. Također bi htjeli to moći raditi i na podmatricama, konkretno u redcima i stupcima. NumPy ima široki spektar funkcija kojima možemo napasti neke standardne probleme. 

In [ ]:
np.max(a)

In [ ]:
np.mean(a)

In [ ]:
np.mean(a, axis=1)  # prosjek redaka, primjetite da axis=1 govori da se krećemo po stupcima, 
                    # to jest agregiramo u smjeru stupaca. To defacto znači da je agregacija ograničena na retke.

In [ ]:
np.sum(a, axis=0)  # zbroj stupaca, axis=0 govori da zbrajamo retke, pa agregacija je lokalizirana po stupcu

In [ ]:
np.max(a, axis=1)

## Operacije

Uz agregacije, želimo i raditi operacije nad `ndarrayevima`, poput zbrajanja, množenja, računanja skalarnih produkata. Uz te, dobro poznate, operacije iz linearne algebre želimo nekada i transformirati arraye po komponentama s nekom proizvoljnom funkciju. Primjerice, želimo za svaki element izračunati sinus, kosinus ili pak neku proizvoljnu funkciju. Prvo ćemo se upoznati s algebarskim operacijama.

In [ ]:
scale_x = np.diag([2,1,1])

x = np.array([1,1,1])

np.dot(scale_x, x)

Što smo ovdje napravili? Sjetimo se linearne algebre, linearni operator možemo zapisati kao matricu. Konkretno smo napravili operator koji x os skalira s brojem 2, a druge dvije osi ostavlja ne promijenjenima. Zatim smo napravili vektor jedinica, i na njega smo djelovali operatorom skaliranja. Očekujemo dobiti vektor koji je dvostruko veći u smjeru x osi, što uistinu i jesmo dobili.

Ovo je primjer umnoška matrice i vektora. NumPy ima funkciju `np.dot`. To je polimorfna funkcija, to jest kao operande može primati, vektor i vektor, matricu i vektor, kao i matricu i matricu. Uobičajeno je za matrične umnoške koristiti `np.matmul` ili operator `@`. Pogledajmo još primjera!

In [ ]:
scale_y = np.diag([1,2,1])

scale_x_y = scale_y @ scale_x 

np.dot(scale_x_y, x)

In [ ]:
vec_1 = np.array([1,1])
vec_2 = np.array([1,0])

np.dot(vec_1, vec_2)

In [ ]:
vec_1 = vec_1.reshape((1,2)) # vektor redak
vec_2 = vec_2.reshape((2,1)) # vektor stupac

vec_2 @ vec_1

In [ ]:
vec_1 @ vec_2

Većina matematičkih numpy funkcija je vektorizirana. Što to znači? Znači da se nad arrayevima primjenjuju *element-wise*. To jest element po element. Pogledajmo:

In [ ]:
scale_y

In [ ]:
np.cos(scale_y)

In [ ]:
np.square(
  np.array([1,2,3])
)

## Broadcasting

`Broadcasting`, ili po hrvatski `odašiljanje`, je način na koji NumPy izvodi operacije koje matematički nisu moguće između takvih tipova. Umjesto stvaranja novih matematičkih ideja, želimo neke standardne probleme, efikasno sintaksno zapisati. Primjerice dodvanje jednog vektor redka svim vektor redcima, naivno bismo izveli petljom:

In [ ]:
arr = np.array([
  [1,2,3],
  [3,2,1]
])

add = np.array([1,1,1])

for i in range(arr.shape[0]):
    arr[i] += add 

arr

Ovaj pristup ima dva problema. Prvi je taj što petlju radimo u neefikasnom Pythonu, umjesto brzom C-u. Naime htjeli bi sve iteracije provoditi indirektno to jest bez eksplictnog iteriranje u Pythonu. Drugi je problem količina sintakse, koju možemo značajno smanjiti. Pogledajmo:

In [ ]:
arr = np.array([
  [1,2,3],
  [3,2,1]
])

arr + add

NumPy provjerom tipova prilikom izvođenja shvati da su tipovi za tu operaciju nekompatibilni, to jest jednodimenzionalni array i dvodimenzionalni array ne možemo zbrojiti. No onda će numpy jednostavno to zbrojiti po komponentama dvodimenzionalnog arraya. Na taj način se iteracija implicitno odvija. 

Broadcasting je kompleksna tema, koja izlazi van opsega ovog uvoda. Bitno je znati da postoji i da se ne iznenadite kako se vektori i matrice ovdje mogu zbrajati. Znatiželjni mogu više saznati na [poveznici](https://numpy.org/doc/stable/user/basics.broadcasting.html)

In [ ]:
x = np.array([
  [1,2],
  [3,4]
])