In [1]:
import numpy as np

### 1. zadatak
stvorite vektor od brojeva od 1 do 50, te ga zatim obrnite.




In [2]:

x = np.arange(1, 51)
x = x[::-1]
print(x)

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2  1]


### 2. zadatak

Izračunajte kut između vektora
$$
\boldsymbol{x} = \begin{bmatrix}
1 \\ 2
\end{bmatrix},
\boldsymbol{y} = \begin{bmatrix}
3 \\ 0
\end{bmatrix}
$$


In [4]:
x = np.array([1,2])
y = np.array([3,0])

cos_alpha = x.dot(y) / np.sqrt((x.dot(x) * y.dot(y)))

alpha = np.arccos(cos_alpha)

print(alpha * 360 / (2 * np.pi))

63.43494882292201


### 3. zadatak

Napišite funkciju koja kao argument prima broj nepoznanica $n$, te listu brojeva $L$ koja predstavlja koeficjente sustava linearnih jednadžbi. 
Konkretno za $n = 2$, sustav bi izgledao kao:
$$
L_0 x + L_1 y = L_2
$$
$$
L_3 x + L_4y = L_5
$$

Kao rezultat, funkcija vraća vektor nepoznanica, ili grešku ako sustav nema (jednistveno) rješenje

In [6]:
def solve(n, L):
    if n * (n + 1) != len(L):
        raise RuntimeError('Invalid list size')
    
    m = np.array(L)
    m = m.reshape(n, n + 1)

    A = m[:, 0 : n]
    b = m[:, n]

    A_inv = np.linalg.inv(A)
    x = A_inv @ b 

    return x

print(solve(2, [2,-1,2,1,-1,4]))

[[ 2 -1]
 [ 1 -1]]
[-2. -6.]


### 4. zadatak

Napravite matricu "šahovnicu". Neka su crna polja broj $1$, a bijela $0$

In [10]:
A = np.zeros(shape=(8,8))

A[::2, ::2] = 1
A[1::2, 1::2] = 1
print(A)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


### 5. zadatak

Iz nasumične matrice dimenzije $n \times n$ odaberite samo one redke čiji je zbroj veći od $4n$. Brojeve generirajte iz intervala $[0,9]$

In [13]:
n = 4
A = np.random.randint(0, 10, size=(n,n))

row_sums = np.sum(A, axis=1)
condition = row_sums > 4 * n

selected = A[condition]

print('Nasumična matrica')
print(A)
print('Sume redaka')
print(row_sums)
print('Odabrani retci')
print(selected)

Nasumična matrica
[[7 5 0 7]
 [0 4 1 2]
 [4 6 7 5]
 [9 1 5 4]]
Sume redaka
[19  7 22 19]
Odabrani retci
[[7 5 0 7]
 [4 6 7 5]
 [9 1 5 4]]


### 6. zadatak
Riješite 5. zadatak ali za sume stupaca, te selektirajte stupce.

In [15]:
n = 4
A = np.random.randint(0, 10, size=(n,n))

col_sums = np.sum(A, axis=0)
condition = col_sums > 4 * n

selected = A[:, condition]

print('Nasumična matrica')
print(A)
print('Sume stupaca')
print(col_sums)
print('Odabrani stupci')
print(selected)

Nasumična matrica
[[8 1 3 0]
 [1 4 7 3]
 [7 1 4 9]
 [9 7 5 5]]
Sume stupaca
[25 13 19 17]
Odabrani stupci
[[8 3 0]
 [1 7 3]
 [7 4 9]
 [9 5 5]]


### 7. zadatak
Generirajte 9 brojeva, te izračunajte prosjek svaka 3

In [18]:
x = np.random.randint(0, 10, 9)
print(x)

x = x.reshape(3, 3)

x = np.mean(x, axis=1)

print(x)

[9 4 4 0 3 3 2 6 2]
[[9 4 4]
 [0 3 3]
 [2 6 2]]
[5.66666667 2.         3.33333333]


### 8. zadatak

Generirajte nasumičan niz $2$-d točaka, te jednu nasumičnu točku $t$. Pronađite najbližu točku niza točki $t$.

In [46]:
points = np.random.uniform(0, 2, size=(20, 2))
point = np.random.uniform(0, 2, size=2)

distances = np.sqrt(np.sum(np.square(points - point), axis=1))


print(points[np.argmin(distances)])
print(point)


[0.95011971 1.35971183]
[0.99049693 1.22156969]


### 9. zadatak

Generirajte 3 nasumične točke te izračunajte povrišnu trokuta kojemu su te točke vrhovi.

In [62]:
points = np.random.uniform(0, 5, size=(3,2))

#points = np.array([[0,0], [3,3], [5,0]])

sides = np.array([
    np.sqrt(np.sum(np.square(points[0] - points[1]))),
    np.sqrt(np.sum(np.square(points[0] - points[2]))),
    np.sqrt(np.sum(np.square(points[1] - points[2]))),
])


s = 0.5 * np.sum(sides)

area = np.sqrt(s * np.product(s - sides))
print(area)

1.8929689534248524
